# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import detection_pb2 as detection__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectionStub:
    """Mirrors valve_stiction_ml.classic.label_window's output directly --
    see docs/V1_PLAN.md. No translation layer to keep in sync separately.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectWindow = channel.unary_unary(
                '/detection.Detection/DetectWindow',
                request_serializer=detection__pb2.WindowRequest.SerializeToString,
                response_deserializer=detection__pb2.WindowResponse.FromString,
                _registered_method=True)


class DetectionServicer:
    """Mirrors valve_stiction_ml.classic.label_window's output directly --
    see docs/V1_PLAN.md. No translation layer to keep in sync separately.
    """

    def DetectWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectWindow,
                    request_deserializer=detection__pb2.WindowRequest.FromString,
                    response_serializer=detection__pb2.WindowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'detection.Detection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('detection.Detection', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Detection:
    """Mirrors valve_stiction_ml.classic.label_window's output directly --
    see docs/V1_PLAN.md. No translation layer to keep in sync separately.
    """

    @staticmethod
    def DetectWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.Detection/DetectWindow',
            detection__pb2.WindowRequest.SerializeToString,
            detection__pb2.WindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
