# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\x12\tdetection\"X\n\rWindowRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\n\n\x02pv\x18\x02 \x03(\x01\x12\n\n\x02op\x18\x03 \x03(\x01\x12\x1c\n\x14window_start_unix_ms\x18\x04 \x01(\x03\"\x8c\x01\n\x0eWindowResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x15\n\rellipse_index\x18\x02 \x01(\x01\x12\x14\n\x0ckano_verdict\x18\x03 \x01(\x08\x12\x14\n\x0chas_activity\x18\x04 \x01(\x08\x12\x10\n\x08rf_label\x18\x05 \x01(\t\x12\x16\n\x0erf_probability\x18\x06 \x01(\x01\x32P\n\tDetection\x12\x43\n\x0c\x44\x65tectWindow\x12\x18.detection.WindowRequest\x1a\x19.detection.WindowResponseB/Z-valve-stiction-pipeline/ingestion/detectionpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-valve-stiction-pipeline/ingestion/detectionpb'
  _globals['_WINDOWREQUEST']._serialized_start=30
  _globals['_WINDOWREQUEST']._serialized_end=118
  _globals['_WINDOWRESPONSE']._serialized_start=121
  _globals['_WINDOWRESPONSE']._serialized_end=261
  _globals['_DETECTION']._serialized_start=263
  _globals['_DETECTION']._serialized_end=343
# @@protoc_insertion_point(module_scope)
