// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: detection.proto

package detectionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WindowRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SensorId          string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Pv                []float64              `protobuf:"fixed64,2,rep,packed,name=pv,proto3" json:"pv,omitempty"`
	Op                []float64              `protobuf:"fixed64,3,rep,packed,name=op,proto3" json:"op,omitempty"`
	WindowStartUnixMs int64                  `protobuf:"varint,4,opt,name=window_start_unix_ms,json=windowStartUnixMs,proto3" json:"window_start_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WindowRequest) Reset() {
	*x = WindowRequest{}
	mi := &file_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowRequest) ProtoMessage() {}

func (x *WindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowRequest.ProtoReflect.Descriptor instead.
func (*WindowRequest) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{0}
}

func (x *WindowRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *WindowRequest) GetPv() []float64 {
	if x != nil {
		return x.Pv
	}
	return nil
}

func (x *WindowRequest) GetOp() []float64 {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *WindowRequest) GetWindowStartUnixMs() int64 {
	if x != nil {
		return x.WindowStartUnixMs
	}
	return 0
}

type WindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // "yes" | "no" | "uncertain"
	EllipseIndex  float64                `protobuf:"fixed64,2,opt,name=ellipse_index,json=ellipseIndex,proto3" json:"ellipse_index,omitempty"`
	KanoVerdict   bool                   `protobuf:"varint,3,opt,name=kano_verdict,json=kanoVerdict,proto3" json:"kano_verdict,omitempty"`
	HasActivity   bool                   `protobuf:"varint,4,opt,name=has_activity,json=hasActivity,proto3" json:"has_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowResponse) Reset() {
	*x = WindowResponse{}
	mi := &file_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowResponse) ProtoMessage() {}

func (x *WindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowResponse.ProtoReflect.Descriptor instead.
func (*WindowResponse) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{1}
}

func (x *WindowResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *WindowResponse) GetEllipseIndex() float64 {
	if x != nil {
		return x.EllipseIndex
	}
	return 0
}

func (x *WindowResponse) GetKanoVerdict() bool {
	if x != nil {
		return x.KanoVerdict
	}
	return false
}

func (x *WindowResponse) GetHasActivity() bool {
	if x != nil {
		return x.HasActivity
	}
	return false
}

var File_detection_proto protoreflect.FileDescriptor

const file_detection_proto_rawDesc = "" +
	"\n" +
	"\x0fdetection.proto\x12\tdetection\"}\n" +
	"\rWindowRequest\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x0e\n" +
	"\x02pv\x18\x02 \x03(\x01R\x02pv\x12\x0e\n" +
	"\x02op\x18\x03 \x03(\x01R\x02op\x12/\n" +
	"\x14window_start_unix_ms\x18\x04 \x01(\x03R\x11windowStartUnixMs\"\x91\x01\n" +
	"\x0eWindowResponse\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12#\n" +
	"\rellipse_index\x18\x02 \x01(\x01R\fellipseIndex\x12!\n" +
	"\fkano_verdict\x18\x03 \x01(\bR\vkanoVerdict\x12!\n" +
	"\fhas_activity\x18\x04 \x01(\bR\vhasActivity2P\n" +
	"\tDetection\x12C\n" +
	"\fDetectWindow\x12\x18.detection.WindowRequest\x1a\x19.detection.WindowResponseB/Z-valve-stiction-pipeline/ingestion/detectionpbb\x06proto3"

var (
	file_detection_proto_rawDescOnce sync.Once
	file_detection_proto_rawDescData []byte
)

func file_detection_proto_rawDescGZIP() []byte {
	file_detection_proto_rawDescOnce.Do(func() {
		file_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_detection_proto_rawDesc), len(file_detection_proto_rawDesc)))
	})
	return file_detection_proto_rawDescData
}

var file_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_detection_proto_goTypes = []any{
	(*WindowRequest)(nil),  // 0: detection.WindowRequest
	(*WindowResponse)(nil), // 1: detection.WindowResponse
}
var file_detection_proto_depIdxs = []int32{
	0, // 0: detection.Detection.DetectWindow:input_type -> detection.WindowRequest
	1, // 1: detection.Detection.DetectWindow:output_type -> detection.WindowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_detection_proto_init() }
func file_detection_proto_init() {
	if File_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detection_proto_rawDesc), len(file_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detection_proto_goTypes,
		DependencyIndexes: file_detection_proto_depIdxs,
		MessageInfos:      file_detection_proto_msgTypes,
	}.Build()
	File_detection_proto = out.File
	file_detection_proto_goTypes = nil
	file_detection_proto_depIdxs = nil
}
