// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: detection.proto

package detectionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Detection_DetectWindow_FullMethodName = "/detection.Detection/DetectWindow"
)

// DetectionClient is the client API for Detection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mirrors valve_stiction_ml.classic.label_window's output directly --
// see docs/V1_PLAN.md. No translation layer to keep in sync separately.
type DetectionClient interface {
	DetectWindow(ctx context.Context, in *WindowRequest, opts ...grpc.CallOption) (*WindowResponse, error)
}

type detectionClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectionClient(cc grpc.ClientConnInterface) DetectionClient {
	return &detectionClient{cc}
}

func (c *detectionClient) DetectWindow(ctx context.Context, in *WindowRequest, opts ...grpc.CallOption) (*WindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WindowResponse)
	err := c.cc.Invoke(ctx, Detection_DetectWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectionServer is the server API for Detection service.
// All implementations must embed UnimplementedDetectionServer
// for forward compatibility.
//
// Mirrors valve_stiction_ml.classic.label_window's output directly --
// see docs/V1_PLAN.md. No translation layer to keep in sync separately.
type DetectionServer interface {
	DetectWindow(context.Context, *WindowRequest) (*WindowResponse, error)
	mustEmbedUnimplementedDetectionServer()
}

// UnimplementedDetectionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectionServer struct{}

func (UnimplementedDetectionServer) DetectWindow(context.Context, *WindowRequest) (*WindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectWindow not implemented")
}
func (UnimplementedDetectionServer) mustEmbedUnimplementedDetectionServer() {}
func (UnimplementedDetectionServer) testEmbeddedByValue()                   {}

// UnsafeDetectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectionServer will
// result in compilation errors.
type UnsafeDetectionServer interface {
	mustEmbedUnimplementedDetectionServer()
}

func RegisterDetectionServer(s grpc.ServiceRegistrar, srv DetectionServer) {
	// If the following call panics, it indicates UnimplementedDetectionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Detection_ServiceDesc, srv)
}

func _Detection_DetectWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServer).DetectWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Detection_DetectWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServer).DetectWindow(ctx, req.(*WindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Detection_ServiceDesc is the grpc.ServiceDesc for Detection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Detection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "detection.Detection",
	HandlerType: (*DetectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectWindow",
			Handler:    _Detection_DetectWindow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detection.proto",
}
